// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsdtihyqxvduwokarzwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZHRpaHlxeHZkdXdva2FyendpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3ODgwNTgsImV4cCI6MjA0OTM2NDA1OH0.buiT1ndBZ39oprk7itJtpb6lClim-JOxBUm7LejWzhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);